#!/usr/bin/env python
"""This program is used to collect DDN Temperatures.
Author: Coady I Kerner
Email: coady.kerner@gmail.com
"""

from __future__ import print_function
from ddn.sfa.api import *
import sqlite3


program_defaults = { 'controller': '14k01-1',
                     'user': 'user',
                     'password': 'user',
                     'dbfile': 'temperature.db',  
                   }

def parse_options():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("-u", "--user",
                        dest="username",
                        default=program_defaults['user'],
                        action='store',
                        help="Username for the account. Default: %(default)s")

    parser.add_argument("-p", "--password",
                        dest="password",
                        default=program_defaults['password'],
                        action='store',
                        help="Password for the account. Default: %(default)s")

    parser.add_argument("-c", "--controller",
                        dest="controller",
                        default=program_defaults['controller'],
                        action='store',
                        help="DDN controller. Default: %(default)s")

    parser.add_argument("--db",
                        dest="dbfile",
                        default=program_defaults['dbfile'],
                        action='store',
                        help="Database file. Default: %(default)s")

    parser.add_argument("-v", "--verbose",
                        dest="verbose",
                        default=False,
                        action='store_true',
                        help="Run in verbose mode. Default: %(default)s")

    parser.add_argument("-D", "--debug",
                        dest="debug",
                        default=False,
                        action='store_true',
                        help="Print Debugging Information. Default: %(default)s")

    args = parser.parse_args()
    return args

def db_connect():
    if args.debug:
       print('Connecting to database.')
    try:
       db = sqlite3.connect(args.dbfile)
    except:
       if args.debug:
          print('Error  connecting to database.')
    if args.debug:
       print('Cursor Declaration')
    sql = db.cursor()
    return (db, sql)

def create_temperatures_table(sql):
    try:
       sql.execute('''
          create table if not exists
          temperatures(ts bigint not null,
             controller text not null,
             enclosure int not null,
             sensor int not null,
             temperature int not null); ''')
       if args.debug:
          print('Temperatures table created.')
    except db.Error, e:
       if args.debug:
          print('Error: ',e.args[0])

def db_disconnect(db):
    if args.debug:
       print('Committing the SQL')
    db.commit()
    if args.debug:
       print('Closing the database.')
    db.close()

def check_temperature():
    """Checks temperature health status.

    Args:
        None

    Returns:
	Nothing

    Raises:
	Nothing

    """
    idx = 0
    while True:
        try:
            enclosure = SFAEnclosure.get(Index=idx)
            t = enclosure.getTemperatureSensors()
            try:
                len(t)
            except:
                if args.verbose:
                   print(idx,'No temperature sensors.')
            else:
                if len(t) >= 0:
                   for dindx in range (len(t)):
                       if args.verbose:
                          print(idx, dindx, t[dindx].CurrentReading)
                       else:
                          if t[dindx].TemperatureWarning:
                             print(idx, dindx, 'Warning.  Temp:', t[dindx].CurrentReading)
                          elif t[dindx].TemperatureFailure:
                             print(idx, dindx, 'Critical.  Temp:', t[dindx].CurrentReading)
                          elif t[dindx].HealthState != 1:
                             print(idx, dindx, 'Sensor Failure.  RC:', t[dindx].HealthState.str())
                          elif t[dindx].PredictFailure:
                             print(idx, dindx, 'Predicted sensor failure.')

        except:
            break

        idx = idx + 1

if __name__ == '__main__':
   args = parse_options()

   (db, sql) = db_connect()

   create_temperatures_table(sql)

   APIConnect("https://"+args.controller, auth=(args.username, args.password))
   
   APIDisconnect()

   db_disconnect(db)
