#!/usr/bin/env python

from __future__ import print_function
from ddn.sfa.api import *
import logging


program_defaults = { 'controller': '14k01-1',
                     'user': 'user',
                     'password': 'user',
                   }

def parse_options():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("-D", "--debug",
                        dest="debug",
                        default=False,
                        action='store_true',
                        help="Print Debugging Information. Default: %(default)s")

    args = parser.parse_args()
    return args


def setup_logging():
    if args.debug:
       loglvl = 'logging.DEBUG'
    else:
       loglvl = 'logging.INFO'
    logging.basicConfig( level = eval(loglvl),
       format = '%(asctime)s %(levelname)-8s %(message)s',
       datefmt = '%Y%m%d %H%M%S',
    )
    logging.debug("Debug mode turned on.")



if __name__ == '__main__':
   args = parse_options()
   #setup_logging()

   APIConnect("https://14k01-1", auth=('user','user'))

   idx = 0
   while True:
      try:
         enclosure = SFAEnclosure.get(Index=idx)
         if enclosure.SerialNumber != None:
            print(idx,'controller',enclosure.SerialNumber)
      except:
         break

      disks = enclosure.getDiskDrives()
      try:
         len(disks)
      except:
         pass
      else:
         if len(disks) >= 0:
            print(idx,len(disks))

      idx = idx + 1




