#!/usr/bin/env python

from __future__ import print_function
from ddn.sfa.api import *
import logging


program_defaults = { 'controller': '14k01-1',
                     'user': 'user',
                     'password': 'user',
                   }

def parse_options():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("-u", "--user",
                        dest="username",
                        default="user",
                        action='store',
                        help="Username for the account. Default: %(default)s")

    parser.add_argument("-p", "--password",
                        dest="password",
                        default='user',
                        action='store',
                        help="Password for the account. Default: %(default)s")
   
    parser.add_argument("-c", "--controller",
                        dest="controller",
                        default='14k01-1',
                        action='store',
                        help="DDN controller. Default: %(default)s")

    parser.add_argument("-D", "--debug",
                        dest="debug",
                        default=False,
                        action='store_true',
                        help="Print Debugging Information. Default: %(default)s")

    args = parser.parse_args()
    return args

if __name__ == '__main__':
   args = parse_options()

   APIConnect("https://"+args.controller, auth=(args.username, args.password))

   idx = 0
   while True:
      try:
         enclosure = SFAEnclosure.get(Index=idx)
         if enclosure.Type == 2:
            print(idx,'controller',enclosure.SerialNumber)
         elif enclosure.Type == 1:
            disks = enclosure.getDiskDrives()
            try:
               len(disks)
            except:
               pass
            else:
               if len(disks) >= 0:
                  print(idx,len(disks))
      except:
         break

      idx = idx + 1

   APIDisconnect()
